name: Deploy Python Lambda

on:
  push:
    branches:
      - main
    paths:
      - '**.py' # Change to the file extension of the language that you are using.

permissions:
      id-token: write
      contents: read

env:
  LAMBDA_FUNCTION_NAME: 'kanye-rest-lambda'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # To fetch the current commit and its parent (so we can compare)

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        audience: sts.amazonaws.com
        aws-region: eu-west-2
        role-to-assume: arn:aws:iam::647746917454:role/inigo-basterretxea-github-actions

    - name: Print changed files # To properly debug what is being deployed (It can be removed).
      run: |
        echo "List of changed files:" 
        echo $(git diff --name-only HEAD^ HEAD)

    - name: Install Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Linting
      run: |
        pip install black
        black data-pipelines/${{ env.LAMBDA_FUNCTION_NAME }} --check

    - name: Publish Lambda Layer
      run: |
        mkdir ${{ env.LAMBDA_FUNCTION_NAME }}-layer
        cd ${{ env.LAMBDA_FUNCTION_NAME }}-layer
        pip install -r ../requirements.txt -t python/lib/python3.12/site-packages/
        zip -r ${{ env.LAMBDA_FUNCTION_NAME }}-layer.zip .
        aws lambda publish-layer-version --layer-name ${{ env.LAMBDA_FUNCTION_NAME }}-layer --zip-file fileb://${{ env.LAMBDA_FUNCTION_NAME }}-layer.zip --compatible-runtimes python3.12


    - name: Deploy Code to Lambda
      run: |
        cd data-pipelines/${{ env.LAMBDA_FUNCTION_NAME }} && zip -j code.zip .
        aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --zip-file fileb://code.zip